import { AuthProvider } from "@/components/AuthProvider";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next apps",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider refetchInterval={30} refetchOnWindowFocus={true}>
          <div className="flex flex-col">
            <header>
              <NavBar />
            </header>
            <main className="flex-1 h-screen ">
              <div className="flex-col items-center justify-between p-24">
                {children}
              </div>
            </main>
          </div>
        </AuthProvider>
        <div>Hello</div>
      </body>
    </html>
  );
}
